### ISSUE TITLE
Melpa installation of skeletor.el should not compile the template elisp files.

### ISSUE THREAD

**Issue by MassimoLauria** [chrisbarrett/skeletor.el#23]
The `skeletor` package includes project templates for, among others, emacs packages. The templates contain stub `elisp` files that should be included in the package, but should not be compiled during package installation.

Currently these stub files are compiled by the melpa installation causing warnings and, worst of all, producing spurious *.elc files to be included in the project template.

In opened an issue  in the melpa repository (https://github.com/milkypostman/melpa/issues/2484) and @purcell suggested it is an upstream bug. He also proposed a solution but I am not very happy with it.

I think the cleanest workaround would be to rename `filename.el` files in the template to `filename__DOD__el`. In this way they are not recognized as elisp files until installed in the actual project.

**Comment by purcell** [comment]
IMO it would be cleaner to just add a `.dir-locals.el` to the `project-skeletons` dir. Having to mangle all the filename when adding project skeletons seems like it would be error-prone.

**Comment by chrisbarrett** [comment]
The `.dir-locals.el` solution seems to work well. :)

**Comment by MassimoLauria** [comment]
Oh, yes. I misinterpreted @purcell solution before. I thought he wanted to put a `.dir-locals.el` in the emacs lisp template directory. That would have been annoying...  But of course the current one is the best solution.
