### ISSUE TITLE
Substitutions are not recursive

### ISSUE THREAD

**Issue by chrisbarrett** [chrisbarrett/skeletor.el#25]
As noted in #2, it's not possible for substitutions (subs) to reference one-another. 

To resolve this, subs will need to maintain an environment. Eval'ing a sub should push it into an environment that can be dereferenced by subsequent subs. Lisp-expr subs in files will probably need to be evaluated last.
# TODO
- [ ] Verify that there is a sound ordering for recursive subs
- [ ] Implement environment extension for subs

**Comment by MassimoLauria** [comment]
That sounds rather complicated: I don't think it is necessary to be able to reference subs in other subs  during the evaluation of the skeletor-define-template command. It would be sufficient to store the textual substitutions in some dictionary and make that available during the substitution application phase.

One caveat is that the argument of the dictionary query would probably contain one of the template strings and we do not want to substitute that before the lisp code is evaluated. I think the correct solution would be not to apply substitutions on the template strings nested inside the lisp code, and let the user specify exactly what he/she wants by coding it up.

**Comment by mohkale** [comment]
Well I'm 5 years late to the party but I've added support for something like this.

With #48 @MassimoLauria can do the original `upcase` substitution like so:

```
foo__(alist-get "__PROJECT-NAME__" skeletor nil nil #'string-equal)__bar
```

The `skeletor` variable now keeps an alist of substitutions (same format as you gave to `skeletor-define-template`).  It's not the prettiest implementation but it works :smile:.
