### ISSUE TITLE
A way to prevent git initialize in some projects?

### ISSUE THREAD

**Issue by OmarAshkar** [chrisbarrett/skeletor.el#52]
Hello,
I am wondering if there is a parameter to set in order to prevent initializing git for some templates. That would be usefull for me.

Thank you for this project!

**Comment by Inc0n** [comment]
There is actually a way to achieve this as of now: pass `:no-git? t` to your template definition, such as `skeletor-define-template`, which is a macro wrapper for `skeletor-define-constructor`. The documentation for this `:no-git` flag can be seen in `skeletor-define-constructor`.

I must add, this peice of documentation cannot be seen in `skeletor-define-template`, I myself had to do some digging to discover this feature, my suggestion would be to reference `skeletor-define-constructor`, i.e. to direct users to it more for and all flags that could be used.
